language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - "6"
before_install:
  - npm i -g yarn --cache-min 999999999
install:
  - yarn install
script:
  - yarn run lint && yarn run test && yarn run build
notifications:
  email:
    on_failure: change